# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Settings common to each job
job_defaults: &job_defaults
  working_directory: ~/angular-docs-es
  docker:
    - image: cimg/node:lts-browsers

orbs:
  node: circleci/node@5.2.0
  build-tools: circleci/build-tools@3.0.0
  browser-tools: circleci/browser-tools@1.4.8

commands:
  # Command for checking out the source code from GitHub. This also ensures that the source code
  # can be merged to the main branch without conflicts.
  checkout_and_rebase:
    description: Checkout and verify clean merge with main
    steps:
      - checkout
      - run:
          name: Set git user.name and user.email for rebase.
          # User is required for rebase.
          command: |
            git config user.name "Admin"
            git config user.email "admin@angular.lat"
      - build-tools/merge-with-parent:
          parent: main
  setup:
    description: 'Set up executor'
    steps:
      - attach_workspace:
          at: ~/
  setup_firebase_auth:
    description: 'Set up Firebase authentication'
    steps:
      - run:
          name: Create a google_service_account.json 
          command: |
            echo $GSA_KEY > $GOOGLE_APPLICATION_CREDENTIALS

# ----------------------------------
# Job definitions.
# ----------------------------------

jobs:
  # ----------------------------------
  # initialize job
  # ----------------------------------
  initialize:
    <<: *job_defaults
    steps:
      - checkout_and_rebase
      - node/install-packages
      - persist_to_workspace:
          root: ~/
          paths:
            - angular-docs-es
  # -----------------------------------
  # Build job.
  # -----------------------------------
  build:
    <<: *job_defaults
    steps:
      - setup
      - checkout
      - run:
          name: Build project in CI mode (pre build)
          command: npm run build:ci
      - run:
          name: Installing packages
          working_directory: ./build
          command: yarn install
      - run:
          name: Build adev-es docs
          working_directory: ./build
          command: yarn bazel build //adev:build --fast_adev --local_ram_resources="HOST_RAM*.90" --jobs=1
      - persist_to_workspace:
          root: ~/
          paths:
            - angular-docs-es/build/dist/bin/adev/build/browser

  # -----------------------------------
  # Firebase deploy to staging job.
  # -----------------------------------
  firebase-deploy-staging:
    <<: *job_defaults
    steps:
      - setup
      - setup_firebase_auth
      - run:
          name: 'Deploy Main Branch to Firebase Hosting'
          command: |
            npm run deploy:staging

workflows:
  build-workflow:
    jobs:
      - initialize
      - build:
          requires:
            - initialize
      - firebase-deploy-staging:
          filters:
            branches:
              only:
                - main
          requires:
            - build